name: Build and Release

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Run tests
      run: mvn clean test
      
    - name: Build project
      run: mvn clean package
      
    - name: Get version from tag
      id: get_version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
        elif [[ $GITHUB_EVENT_NAME == "release" ]]; then
          VERSION=${{ github.event.release.tag_name }}
          VERSION=${VERSION#v}
        else
          VERSION="snapshot-$(date +%Y%m%d-%H%M%S)"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"
        
    - name: Rename JAR with version
      run: |
        VERSION="${{ steps.get_version.outputs.version }}"
        cp target/cdoc-encryptor-*-jar-with-dependencies.jar  cdoc-encryptor-${VERSION}.jar
        ls -la *.jar
        
    - name: Upload JAR to release (if release event)
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: cdoc-encryptor-${{ steps.get_version.outputs.version }}.jar
        asset_name: cdoc-encryptor-${{ steps.get_version.outputs.version }}.jar
        asset_content_type: application/java-archive
        
    - name: Create release for tag push
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: cdoc-encryptor-${{ steps.get_version.outputs.version }}.jar
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload artifacts (for manual workflow dispatch)
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-artifact@v4
      with:
        name: cdoc-encryptor-${{ steps.get_version.outputs.version }}
        path: cdoc-encryptor-${{ steps.get_version.outputs.version }}.jar
        retention-days: 30